name: Linting, import orders, and types

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: flake8 . --count --statistics --max-line-length 120
      - name: Import orders with isort
        run: isort --check-only -diff
      - name: Type check with mypy
        run: mypy .
